promptsDir: "./prompts"
outputDir: "./results"

models:
  - name: "gpt-4o-temp0.2"
    provider: "openai"
    modelName: "gpt-4o"
    temperature: 0.2
    maxTokens: 5000
  - name: "gpt-4o-temp0.1"
    provider: "openai"
    modelName: "gpt-4o"
    temperature: 0.1
    maxTokens: 5000
  - name: "o3-mini-temp0"
    provider: "openai"
    modelName: "o3-mini"
    temperature: 0.0
    maxTokens: 5000

evaluationParams:
  repeatCount: 2
  concurrency: 2
  timeoutSeconds: 60
